---
collections:
  - name: https://github.com/k3s-io/k3s-ansible.git
    type: git
    version: 1.1.0
  - name: community.docker
    version: 5.0.1
  - name: community.general
    version: 12.0.1

roles:
  - name: geerlingguy.docker
    version: 7.8.0